# Generated by Django 3.2.4 on 2021-06-26 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_objects', '0004_auto_20210626_1547'),
        ('user_score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joi', models.IntegerField()),
                ('empathy', models.IntegerField()),
                ('thoughtfulness', models.IntegerField()),
                ('reviewed_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_objects.museumobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Exhibit',
        ),
    ]
