# Generated by Django 3.2.4 on 2021-06-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_objects', '0004_auto_20210626_1312'),
        ('get_objects', '0004_auto_20210626_1547'),
    ]

    operations = [
    ]
